/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    news: News;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale:
    | ('false' | 'none' | 'null')
    | false
    | null
    | ('en' | 'zh' | 'fr' | 'es' | 'ru' | 'ar' | 'ja' | 'ms' | 'id')
    | ('en' | 'zh' | 'fr' | 'es' | 'ru' | 'ar' | 'ja' | 'ms' | 'id')[];
  globals: {
    'common-content': CommonContent;
    'home-content': HomeContent;
    'about-content': AboutContent;
    'products-page-content': ProductsPageContent;
    'manufacturing-content': ManufacturingContent;
    'oem-odm-content': OemOdmContent;
    'quality-content': QualityContent;
    'contact-content': ContactContent;
    'business-card-content': BusinessCardContent;
  };
  globalsSelect: {
    'common-content': CommonContentSelect<false> | CommonContentSelect<true>;
    'home-content': HomeContentSelect<false> | HomeContentSelect<true>;
    'about-content': AboutContentSelect<false> | AboutContentSelect<true>;
    'products-page-content': ProductsPageContentSelect<false> | ProductsPageContentSelect<true>;
    'manufacturing-content': ManufacturingContentSelect<false> | ManufacturingContentSelect<true>;
    'oem-odm-content': OemOdmContentSelect<false> | OemOdmContentSelect<true>;
    'quality-content': QualityContentSelect<false> | QualityContentSelect<true>;
    'contact-content': ContactContentSelect<false> | ContactContentSelect<true>;
    'business-card-content': BusinessCardContentSelect<false> | BusinessCardContentSelect<true>;
  };
  locale: 'en' | 'zh' | 'fr' | 'es' | 'ru' | 'ar' | 'ja' | 'ms' | 'id';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'editor' | 'publisher' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * 描述图片内容，供无障碍阅读器和图片无法加载时使用。
   */
  alt: string;
  prefix?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * 每个产品只维护一条记录；使用右上角语言选择器编辑九种语言。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * 网站当前支持的三个固定产品页面。
   */
  slug: 'lvt-flooring' | 'pet-wall-coverings' | 'pet-carpet-coverings';
  name: string;
  category: string;
  headline: string;
  short: string;
  texture: 'lvt' | 'wall' | 'carpet';
  description: string[];
  features?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  applications?: string[] | null;
  formats?: string[] | null;
  specs?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  compliance?: string[] | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 事实依据只写公开安全的核实说明，不要粘贴内部资料或敏感信息。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  /**
   * 例如 new-showroom-opening。发布后不要随意修改。
   */
  slug: string;
  title: string;
  publishedAt: string;
  category: 'Events' | 'Manufacturing' | 'Sustainability' | 'Company';
  excerpt: string;
  body: string[];
  coverImage?: (number | null) | Media;
  approvedBy?: string | null;
  approvalReference?: string | null;
  sourceNotes?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  slug?: T;
  name?: T;
  category?: T;
  headline?: T;
  short?: T;
  texture?: T;
  description?: T;
  features?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  applications?: T;
  formats?: T;
  specs?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  compliance?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  slug?: T;
  title?: T;
  publishedAt?: T;
  category?: T;
  excerpt?: T;
  body?: T;
  coverImage?: T;
  approvedBy?: T;
  approvalReference?: T;
  sourceNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * 网站 SEO、导航、通用按钮、行动号召和页脚。 先选择右上角语言；草稿不会影响正式网站。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "common-content".
 */
export interface CommonContent {
  id: number;
  siteMeta: {
    title: string;
    description: string;
  };
  nav: {
    about: string;
    products: string;
    manufacturing: string;
    quality: string;
    oemOdm: string;
    news: string;
    contact: string;
  };
  common: {
    skipToContent: string;
    allProducts: string;
    allNews: string;
    readArticle: string;
    requestSamples: string;
    moreAboutHailan: string;
    exploreProducts: string;
    ourManufacturing: string;
    languageLabel: string;
  };
  cta: {
    title: string;
    lede: string;
    button: string;
  };
  footer: {
    tagline: string;
    products: string;
    company: string;
    headquarters: string;
    address?: string[] | null;
    rights: string;
    signoff: string;
    globalInquiries: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 按访客从上到下看到的顺序编辑首页。 先选择右上角语言；草稿不会影响正式网站。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content".
 */
export interface HomeContent {
  id: number;
  hero: {
    kicker: string;
    headlineLine1: string;
    headlineLine2: string;
    lede: string;
    badge: string;
    scroll: string;
  };
  intro: {
    eyebrow: string;
    title: string;
    para1: string;
    para2: string;
    stats: {
      countries: string;
      facility: string;
      facilityUnit: string;
      capacity: string;
      team: string;
    };
  };
  productsHome: {
    eyebrow: string;
    title: string;
    lede: string;
  };
  productLines: {
    'lvt-flooring': {
      name: string;
      category: string;
      short: string;
      chips?: string[] | null;
    };
    'pet-wall-coverings': {
      name: string;
      category: string;
      short: string;
      chips?: string[] | null;
    };
    'pet-carpet-coverings': {
      name: string;
      category: string;
      short: string;
      chips?: string[] | null;
    };
  };
  manufacturingHome: {
    eyebrow: string;
    title: string;
    lede: string;
    link: string;
    pillars?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    process?: string[] | null;
  };
  why: {
    eyebrow: string;
    title: string;
    lede: string;
    reasons?:
      | {
          title: string;
          text: string;
          proof: string;
          id?: string | null;
        }[]
      | null;
  };
  markets: {
    eyebrow: string;
    title: string;
    lede: string;
    regions?:
      | {
          name: string;
          markets: string;
          id?: string | null;
        }[]
      | null;
    figures?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  newsHome: {
    eyebrow: string;
    title: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 公司故事、数据、价值观、时间线和合规信息。 先选择右上角语言；草稿不会影响正式网站。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-content".
 */
export interface AboutContent {
  id: number;
  about: {
    meta: {
      title: string;
      description: string;
    };
    hero: {
      eyebrow: string;
      title: string;
      lede: string;
    };
    story: {
      eyebrow: string;
      title: string;
      para1: string;
      para2: string;
      para3: string;
      stats: {
        founded: string;
        facility: string;
        lines: string;
        team: string;
      };
    };
    values: {
      eyebrow: string;
      title: string;
      lede: string;
      items?:
        | {
            title: string;
            text: string;
            id?: string | null;
          }[]
        | null;
    };
    timeline: {
      eyebrow: string;
      title: string;
      items?:
        | {
            year: string;
            title: string;
            text: string;
            id?: string | null;
          }[]
        | null;
    };
    compliance: {
      eyebrow: string;
      title: string;
      text: string;
    };
    cta: {
      title: string;
      lede: string;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 产品列表页的标题、说明和行动号召；具体产品在“产品”中编辑。 先选择右上角语言；草稿不会影响正式网站。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-page-content".
 */
export interface ProductsPageContent {
  id: number;
  productsPage: {
    meta: {
      title: string;
      description: string;
    };
    hero: {
      eyebrow: string;
      title: string;
      lede: string;
    };
    explore: string;
    roadmap: {
      eyebrow: string;
      title: string;
      text: string;
      link: string;
    };
    cta: {
      title: string;
      lede: string;
      button: string;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 制造流程、自动化能力和物流信息。 先选择右上角语言；草稿不会影响正式网站。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manufacturing-content".
 */
export interface ManufacturingContent {
  id: number;
  manufacturingPage: {
    meta: {
      title: string;
      description: string;
    };
    hero: {
      eyebrow: string;
      title: string;
      lede: string;
    };
    capabilities?: string[] | null;
    process: {
      eyebrow: string;
      title: string;
      lede: string;
      steps?:
        | {
            title: string;
            text: string;
            id?: string | null;
          }[]
        | null;
    };
    automation: {
      eyebrow: string;
      title: string;
      lede: string;
      link: string;
      items?:
        | {
            title: string;
            text: string;
            id?: string | null;
          }[]
        | null;
    };
    logistics: {
      eyebrow: string;
      title: string;
      text: string;
      points?: string[] | null;
    };
    cta: {
      title: string;
      lede: string;
      button: string;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 定制合作流程、服务和保障。 先选择右上角语言；草稿不会影响正式网站。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oem-odm-content".
 */
export interface OemOdmContent {
  id: number;
  oemOdmPage: {
    meta: {
      title: string;
      description: string;
    };
    hero: {
      eyebrow: string;
      title: string;
      lede: string;
    };
    process: {
      eyebrow: string;
      title: string;
      lede: string;
      steps?:
        | {
            title: string;
            meta: string;
            text: string;
            id?: string | null;
          }[]
        | null;
    };
    services: {
      eyebrow: string;
      title: string;
      items?:
        | {
            title: string;
            text: string;
            id?: string | null;
          }[]
        | null;
    };
    assurances: {
      eyebrow: string;
      title: string;
      intro: string;
      points?: string[] | null;
    };
    cta: {
      title: string;
      lede: string;
      button: string;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 质量关卡、实验室、认证和追溯信息。 先选择右上角语言；草稿不会影响正式网站。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quality-content".
 */
export interface QualityContent {
  id: number;
  qualityPage: {
    meta: {
      title: string;
      description: string;
    };
    hero: {
      eyebrow: string;
      title: string;
      lede: string;
    };
    gates: {
      eyebrow: string;
      title: string;
      lede: string;
      gateLabel: string;
      items?:
        | {
            title: string;
            text: string;
            id?: string | null;
          }[]
        | null;
    };
    lab: {
      eyebrow: string;
      title: string;
      lede: string;
      caption: string;
      colTest: string;
      colMethod: string;
      tests?: string[] | null;
    };
    trace: {
      eyebrow: string;
      title: string;
      para1: string;
      para2: string;
    };
    certs: {
      eyebrow: string;
      title: string;
      lede: string;
    };
    cta: {
      title: string;
      lede: string;
      button: string;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 联系表单、咨询方式、来访和工作时间。 先选择右上角语言；草稿不会影响正式网站。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-content".
 */
export interface ContactContent {
  id: number;
  contactPage: {
    meta: {
      title: string;
      description: string;
    };
    hero: {
      eyebrow: string;
      title: string;
      lede: string;
    };
    inquiries: string;
    hq: string;
    hours: string;
    visits: string;
    nextTitle: string;
    expectations?:
      | {
          title: string;
          text: string;
          id?: string | null;
        }[]
      | null;
    form: {
      heading: string;
      intro: string;
      name: string;
      namePlaceholder: string;
      company: string;
      companyPlaceholder: string;
      email: string;
      emailPlaceholder: string;
      country: string;
      countryPlaceholder: string;
      inquiry: string;
      inquiryTypes?: string[] | null;
      productsInterest: string;
      message: string;
      messagePlaceholder: string;
      submit: string;
      note: string;
      status: string;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * 林子越商务名片页面的文案与联系方式标签。 先选择右上角语言；草稿不会影响正式网站。
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-card-content".
 */
export interface BusinessCardContent {
  id: number;
  linusPage: {
    meta: {
      title: string;
      description: string;
    };
    hero: {
      role: string;
    };
    getInTouch: string;
    labels: {
      email: string;
    };
    wecomValue: string;
    wecomNote: string;
    linkedinValue: string;
    companyTagline: string;
    wecomHeading: string;
    wecomScan: string;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "common-content_select".
 */
export interface CommonContentSelect<T extends boolean = true> {
  siteMeta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  nav?:
    | T
    | {
        about?: T;
        products?: T;
        manufacturing?: T;
        quality?: T;
        oemOdm?: T;
        news?: T;
        contact?: T;
      };
  common?:
    | T
    | {
        skipToContent?: T;
        allProducts?: T;
        allNews?: T;
        readArticle?: T;
        requestSamples?: T;
        moreAboutHailan?: T;
        exploreProducts?: T;
        ourManufacturing?: T;
        languageLabel?: T;
      };
  cta?:
    | T
    | {
        title?: T;
        lede?: T;
        button?: T;
      };
  footer?:
    | T
    | {
        tagline?: T;
        products?: T;
        company?: T;
        headquarters?: T;
        address?: T;
        rights?: T;
        signoff?: T;
        globalInquiries?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-content_select".
 */
export interface HomeContentSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        kicker?: T;
        headlineLine1?: T;
        headlineLine2?: T;
        lede?: T;
        badge?: T;
        scroll?: T;
      };
  intro?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        para1?: T;
        para2?: T;
        stats?:
          | T
          | {
              countries?: T;
              facility?: T;
              facilityUnit?: T;
              capacity?: T;
              team?: T;
            };
      };
  productsHome?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lede?: T;
      };
  productLines?:
    | T
    | {
        'lvt-flooring'?:
          | T
          | {
              name?: T;
              category?: T;
              short?: T;
              chips?: T;
            };
        'pet-wall-coverings'?:
          | T
          | {
              name?: T;
              category?: T;
              short?: T;
              chips?: T;
            };
        'pet-carpet-coverings'?:
          | T
          | {
              name?: T;
              category?: T;
              short?: T;
              chips?: T;
            };
      };
  manufacturingHome?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lede?: T;
        link?: T;
        pillars?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        process?: T;
      };
  why?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lede?: T;
        reasons?:
          | T
          | {
              title?: T;
              text?: T;
              proof?: T;
              id?: T;
            };
      };
  markets?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        lede?: T;
        regions?:
          | T
          | {
              name?: T;
              markets?: T;
              id?: T;
            };
        figures?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  newsHome?:
    | T
    | {
        eyebrow?: T;
        title?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-content_select".
 */
export interface AboutContentSelect<T extends boolean = true> {
  about?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
            };
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lede?: T;
            };
        story?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              para1?: T;
              para2?: T;
              para3?: T;
              stats?:
                | T
                | {
                    founded?: T;
                    facility?: T;
                    lines?: T;
                    team?: T;
                  };
            };
        values?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lede?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
            };
        timeline?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    year?: T;
                    title?: T;
                    text?: T;
                    id?: T;
                  };
            };
        compliance?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              text?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              lede?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products-page-content_select".
 */
export interface ProductsPageContentSelect<T extends boolean = true> {
  productsPage?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
            };
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lede?: T;
            };
        explore?: T;
        roadmap?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              text?: T;
              link?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              lede?: T;
              button?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manufacturing-content_select".
 */
export interface ManufacturingContentSelect<T extends boolean = true> {
  manufacturingPage?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
            };
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lede?: T;
            };
        capabilities?: T;
        process?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lede?: T;
              steps?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
            };
        automation?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lede?: T;
              link?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
            };
        logistics?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              text?: T;
              points?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              lede?: T;
              button?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oem-odm-content_select".
 */
export interface OemOdmContentSelect<T extends boolean = true> {
  oemOdmPage?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
            };
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lede?: T;
            };
        process?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lede?: T;
              steps?:
                | T
                | {
                    title?: T;
                    meta?: T;
                    text?: T;
                    id?: T;
                  };
            };
        services?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
            };
        assurances?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              intro?: T;
              points?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              lede?: T;
              button?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quality-content_select".
 */
export interface QualityContentSelect<T extends boolean = true> {
  qualityPage?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
            };
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lede?: T;
            };
        gates?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lede?: T;
              gateLabel?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
            };
        lab?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lede?: T;
              caption?: T;
              colTest?: T;
              colMethod?: T;
              tests?: T;
            };
        trace?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              para1?: T;
              para2?: T;
            };
        certs?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lede?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              lede?: T;
              button?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-content_select".
 */
export interface ContactContentSelect<T extends boolean = true> {
  contactPage?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
            };
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              lede?: T;
            };
        inquiries?: T;
        hq?: T;
        hours?: T;
        visits?: T;
        nextTitle?: T;
        expectations?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        form?:
          | T
          | {
              heading?: T;
              intro?: T;
              name?: T;
              namePlaceholder?: T;
              company?: T;
              companyPlaceholder?: T;
              email?: T;
              emailPlaceholder?: T;
              country?: T;
              countryPlaceholder?: T;
              inquiry?: T;
              inquiryTypes?: T;
              productsInterest?: T;
              message?: T;
              messagePlaceholder?: T;
              submit?: T;
              note?: T;
              status?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "business-card-content_select".
 */
export interface BusinessCardContentSelect<T extends boolean = true> {
  linusPage?:
    | T
    | {
        meta?:
          | T
          | {
              title?: T;
              description?: T;
            };
        hero?:
          | T
          | {
              role?: T;
            };
        getInTouch?: T;
        labels?:
          | T
          | {
              email?: T;
            };
        wecomValue?: T;
        wecomNote?: T;
        linkedinValue?: T;
        companyTagline?: T;
        wecomHeading?: T;
        wecomScan?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}